FORMAT: 1A
HOST: https://my-stackoverflow-lite-api.herokuapp.com

# Stackoverflow-Lite

StackOverflow-Lite is an app that allows a user to post questions, 
answer other questions posted on the forum. 
Users can accept answers to their questions and view various statistics involved 
such as the number of questions asked or answered.
The api provides endpoints for signup, login, logout, retrieve all or 
a single question, post a question, answer a question and 
update an answer or accept an answer.

## Register User [/api/v1/auth/signup]
A user may signup using this action. 
It takes a JSON object containing user information.
### Add a new user [POST]

+ Request (application/json)

    + Body
    
            {
                "name":"Jay", "username":"jay", "email":"jay@abc.com",
                "password":"Hello123", "confirm_password":"Hello123"
            }

+ Response 201 (application/json)

    + Body

            {
                "message":"Welcome jay!"
            }


## User Login [/api/v1/auth/login]
User may login by providing username and password.
### Login user [POST]

+ Request (application/json)

    + Body
    
            {
                "username":"jay", "password":"Hello123"
            }

+ Response 200 (application/json)

    + Body

            {
                "message" : "Welcome back, jay!"
                "token" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
            }

## User Logout [/api/v1/auth/logout]
A user needs to be logged in to access this action using the token provided during login.
### Logout user [POST]

+ Request (application/json)

    + Headers
    
                Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJlYTQ0ZjA5YS01MTg2LTRjZWMtODdjMi04MjE3MWJkODg1NTciLCJleHAiOjE1MjI2MTQ0MTYsImZyZXNoIjpmYWxzZSwiaWF0IjoxNTIyNjEzNTE2LCJ0eXBlIjoiYWNjZXNzIiwibmJmIjoxNTIyNjEzNTE2LCJpZGVudGl0eSI6Im1pa2V5In0.GEiVrXXx9-j6KcrMBGfDgETZIBtdWGjCyExkKkTgXi4
            

+ Response 200 (application/json)

    + Body

            {
                "message" : "Leaving so soon?"
            }
            
## Questions Collection [/api/v1/questions]

### List All Questions [GET]
Retreive all questions

+ Response 200 (application/json)

        [
            {
                "accepted_answer": "none",
                "answers": [
                    {
                        "papi": "Open a shop on shopify"
                    }
                ],
                "content": "Hello, I would like to know how to sell fruits",
                "title": "How to sell?",
                "username": "jay"
            },
            {
                "accepted_answer": "none",
                "answers": [],
                "content": "Whats the price on they new J's",
                "title": "Addidas shoes",
                "username": "larry"
            },
            {
                "accepted_answer": "none",
                "answers": [],
                "content": "How long is the seinfield series?",
                "title": "Seinfield series",
                "username": "shuri"
            }
        ]

### Create a New Question [POST]

This Action requires a user to be logged in. The user may post their own question using this action. It takes a JSON
object containing the question title and question content

+ Request (application/json)

    + Headers
    
            Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJlYTQ0ZjA5YS01MTg2LTRjZWMtODdjMi04MjE3MWJkODg1NTciLCJleHAiOjE1MjI2MTQ0MTYsImZyZXNoIjpmYWxzZSwiaWF0IjoxNTIyNjEzNTE2LCJ0eXBlIjoiYWNjZXNzIiwibmJmIjoxNTIyNjEzNTE2LCJpZGVudGl0eSI6Im1pa2V5In0.GEiVrXXx9-j6KcrMBGfDgETZIBtdWGjCyExkKkTgXi4
            
                
    + Body
    
            {
                "title" : "How to sell?", 
                "content" : "Hello, I would like to know how to sell fruits"
            }

+ Response 201 (application/json)

    + Headers

            Location: /api/v1/questions/0

    + Body

            {
                "message": "How to sell?, Posted!"
            }
        
## Single Question Actions [/api/v1/questions/<question_id>]
### List Single Questions [GET]
Retreive single question using question id.

+ Response 200 (application/json)

        {
            "accepted_answer": "none",
            "answers": [
                {
                    "njery": "Fly to Miami"
                }
            ],
            "content": "Hello, I would like to know how to sell fruits",
            "title": "How to sell?",
            "username": "njery"
        }

### Delete Question [DELETE]
This Action requires a user to be logged in. They can delete their question using question id.
+ Request (application/json)

    + Headers
    
            Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJlYTQ0ZjA5YS01MTg2LTRjZWMtODdjMi04MjE3MWJkODg1NTciLCJleHAiOjE1MjI2MTQ0MTYsImZyZXNoIjpmYWxzZSwiaWF0IjoxNTIyNjEzNTE2LCJ0eXBlIjoiYWNjZXNzIiwibmJmIjoxNTIyNjEzNTE2LCJpZGVudGl0eSI6Im1pa2V5In0.GEiVrXXx9-j6KcrMBGfDgETZIBtdWGjCyExkKkTgXi4
            
                
+ Response 200 (application/json)

        {
            "message": "Question #<question_id> Deleted Successfully"
        }
        
## Answers [/api/v1/questions/<question_id>/answers]
### Post Answer [POST]
This Action requires a user to be logged in. They can post an answer to a question.
+ Request (application/json)

    + Headers
    
            Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJlYTQ0ZjA5YS01MTg2LTRjZWMtODdjMi04MjE3MWJkODg1NTciLCJleHAiOjE1MjI2MTQ0MTYsImZyZXNoIjpmYWxzZSwiaWF0IjoxNTIyNjEzNTE2LCJ0eXBlIjoiYWNjZXNzIiwibmJmIjoxNTIyNjEzNTE2LCJpZGVudGl0eSI6Im1pa2V5In0.GEiVrXXx9-j6KcrMBGfDgETZIBtdWGjCyExkKkTgXi4
            
    + Body
    
            {
                "content": "Sample answer1"
            }
                
+ Response 201 (application/json)

            {
                "message": "Answer Posted!"
            }

### Get Answers [GET]
This action returns all answers to a particular question
+ Response 200 (application/json)

            [
                {
                    "user1": "Sample answers content1"
                },
                {
                    "user2": "Sample answers content2"
                }
            ]

## Accept or Update Answer [/api/v1/questions/<question_id>/answers/<answer_id>]
### Accept or Update Answer [PUT]
This Action requires a user to be logged in. If the user is the owner of the question they can accept an answer using this action. If the user is the owner of the answer they can update their answer using this action
+ Request (application/json)

    + Headers
    
            Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJlYTQ0ZjA5YS01MTg2LTRjZWMtODdjMi04MjE3MWJkODg1NTciLCJleHAiOjE1MjI2MTQ0MTYsImZyZXNoIjpmYWxzZSwiaWF0IjoxNTIyNjEzNTE2LCJ0eXBlIjoiYWNjZXNzIiwibmJmIjoxNTIyNjEzNTE2LCJpZGVudGl0eSI6Im1pa2V5In0.GEiVrXXx9-j6KcrMBGfDgETZIBtdWGjCyExkKkTgXi4
            
        
+ Response 200 (application/json)
            
        { 
        "message": "Answer #<answer_id> accepted!" 
        }

## Upvote answer [/api/v1/questions/<question_id>/answers/<answer_id>/upvote]
### Upvote [POST]
This Action requires a user to be logged in. The owner of an answer cannot vote on their own answer.
+ Request (application/json)

    + Headers
    
            Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJlYTQ0ZjA5YS01MTg2LTRjZWMtODdjMi04MjE3MWJkODg1NTciLCJleHAiOjE1MjI2MTQ0MTYsImZyZXNoIjpmYWxzZSwiaWF0IjoxNTIyNjEzNTE2LCJ0eXBlIjoiYWNjZXNzIiwibmJmIjoxNTIyNjEzNTE2LCJpZGVudGl0eSI6Im1pa2V5In0.GEiVrXXx9-j6KcrMBGfDgETZIBtdWGjCyExkKkTgXi4
            
+ Response 200 (application/json)
            
        { 
        "message": "Thanks for contributing!" 
        }                

## Downvote answer [/api/v1/questions/<question_id>/answers/<answer_id>/downvote]
### Downvote [POST]
This Action requires a user to be logged in. The owner of an answer cannot vote on their own answer.
+ Request (application/json)

    + Headers
    
            Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJlYTQ0ZjA5YS01MTg2LTRjZWMtODdjMi04MjE3MWJkODg1NTciLCJleHAiOjE1MjI2MTQ0MTYsImZyZXNoIjpmYWxzZSwiaWF0IjoxNTIyNjEzNTE2LCJ0eXBlIjoiYWNjZXNzIiwibmJmIjoxNTIyNjEzNTE2LCJpZGVudGl0eSI6Im1pa2V5In0.GEiVrXXx9-j6KcrMBGfDgETZIBtdWGjCyExkKkTgXi4
            
+ Response 200 (application/json)
            
        { 
        "message": "Thanks for contributing!" 
        }                

## User Questions [/api/v1/users/questions]
### User's questions [GET]
This Action requires a user to be logged in. User can view all questions they have posted.
+ Request (application/json)

    + Headers
    
            Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJlYTQ0ZjA5YS01MTg2LTRjZWMtODdjMi04MjE3MWJkODg1NTciLCJleHAiOjE1MjI2MTQ0MTYsImZyZXNoIjpmYWxzZSwiaWF0IjoxNTIyNjEzNTE2LCJ0eXBlIjoiYWNjZXNzIiwibmJmIjoxNTIyNjEzNTE2LCJpZGVudGl0eSI6Im1pa2V5In0.GEiVrXXx9-j6KcrMBGfDgETZIBtdWGjCyExkKkTgXi4
            
+ Response 200 (application/json)

            [
                {
                    "question_id": 2,
                    "title": "Sample question2 title",
                    "content": "Sample question content",
                    "answers": 0
                },
                {
                    "question_id": 3,
                    "title": "Sample question3 title",
                    "content": "Sample question content",
                    "answers": 0
                }
            ]

## Answer Comments [/api/v1/questions/<question_id>/answers/<answer_id>/comments]
### Post a comment [POST]
This Action requires a user to be logged in. User can post a comment to an answer.
+ Request (application/json)

    + Headers
    
            Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJlYTQ0ZjA5YS01MTg2LTRjZWMtODdjMi04MjE3MWJkODg1NTciLCJleHAiOjE1MjI2MTQ0MTYsImZyZXNoIjpmYWxzZSwiaWF0IjoxNTIyNjEzNTE2LCJ0eXBlIjoiYWNjZXNzIiwibmJmIjoxNTIyNjEzNTE2LCJpZGVudGl0eSI6Im1pa2V5In0.GEiVrXXx9-j6KcrMBGfDgETZIBtdWGjCyExkKkTgXi4
            
    + Body
    
            {
                "content" : "Sample comment1"
            }
+ Response 201 (application/json)

            { 
                "message": "Comment posted!" 
            }
            
### Get all comments for an answer [GET]
+ Response 200 (application/json)

            [
                {
                    "user": "sample updated comment"
                }
            ]
        
## Edit Comment [/api/v1/questions/<question_id>/answers/<answer_id>/comments/<comments_id>]
### Edit comment [PUT]
This Action requires a user to be logged in. User can update a comment they had posted.
+ Request (application/json)

    + Headers
    
            Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJlYTQ0ZjA5YS01MTg2LTRjZWMtODdjMi04MjE3MWJkODg1NTciLCJleHAiOjE1MjI2MTQ0MTYsImZyZXNoIjpmYWxzZSwiaWF0IjoxNTIyNjEzNTE2LCJ0eXBlIjoiYWNjZXNzIiwibmJmIjoxNTIyNjEzNTE2LCJpZGVudGl0eSI6Im1pa2V5In0.GEiVrXXx9-j6KcrMBGfDgETZIBtdWGjCyExkKkTgXi4
            
    + Body
    
            {
                "content" : "Sample update comment1"
            }
+ Response 200 (application/json)

            { 
                "message": "Comment updated!" 
            }
            
## Search Question [/api/v1/questions/search?limit=10]
### Search a question [POST]
This action allows a user to search for a question by title. A limit has to be passed in the URL arguments. 
If the exact title is found id of the question is returned, if not a list of 10 closest matches is returned.

+ Request (application/json)
    
    + Body
    
            {
                "content" : "question title"
            }
            
+ Response 200 (application/json)

            [
                "Sample question4 title",
                "Sample question3 title",
                "Sample question2 title",
                "Sample question1 title"
            ]
